scanner:
    diff_only: True  # If True, only the diff is scanned.
    linter: flake8

flake8:  # Valid if scanner.linter is flake8
    max-line-length: 89
    ignore: [W503]
    exclude: []
    count: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []
