---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-xml
      - id: check-json
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--django']
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
...
