language: python
sudo: false
arch:
- amd64
- ppc64le
sudo: false
python:
- '3.5'
- '3.4'
jobs:
  include:
   - arch : amd64
     python : '2.7'
     dist: bionic
   - arch : amd64
     python : pypy3
   - arch : ppc64le
     dist: bionic
     python : '2.7'
install:
- pip install coveralls
- pip install pep8
script:
- pep8 --exclude test_main.py pygeoif
- coverage run --source=pygeoif setup.py test
after_success: coveralls
notifications:
  email:
  - christian.ledermann@gmail.com
deploy:
  provider: pypi
  user: Chistian.Ledermann
  password:
    secure: TTQcCL3J19iBOdMzOBYdft9XWsV9Ft1GLAzC3nMYX5aQPjB2UHwwvASTUlB8WCpKvDuJfPJxhkh8r2PWT31fyFjskcTwn2Z4WVP5xtt+/qZYu99gf59AxNXjOa+RBPkduVqjBxa+C2y/LcbVd011VmfKV1Usr8a16mf5NsLUjPo=
  on:
    tags: true
    repo: cleder/pygeoif
