# This workflow will install Python dependencies,
# run tests and lint with a variety of Python versions
---
name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cpython:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Test with pytest
        run: |
          pytest pygeoif --cov=pygeoif
      - name: Typecheck
        run: |
          mypy pygeoif
      - name: Linting
        run: |
          flake8 pygeoif
          black --check pygeoif
          yamllint .github/workflows/
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  pypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pypy-version: ['pypy-3.6', 'pypy-3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.pypy-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pypy-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest pygeoif
...
